services:
  external:
    container_name: my-port 
    # The name of the image that will be created when building this container
    image: port/port
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000
